<div class="gallery">
	<div class="row">
		<ul id="galleryImageList" class="img-list">
		<?php 
			$i=0;
			foreach($this->viewFields['Images'] as $filename)
			{
			?>
				<li>
					<img id="small-gallery-image_<?php echo $i ?>" onclick="embiggen(<?php echo $i ?>)" src="<?php echo $filename ?>" alt="img" width="150">
					<img class="hide" id="large-gallery-image_<?php echo $i ?>" onclick="ensmallen(<?php echo $i ?>)" src="<?php echo $filename ?>" alt="img">
				</li>
			<?php
			$i++;
			}
		?>
		</ul>
	</div>
	<div class="row">
		<form action="index.php?controller=Gallery&action=Upload" method="post" enctype="multipart/form-data">
		    Select image to upload:
		    <input type="file" name="fileToUpload" id="fileToUpload">
		    <input type="submit" value="Upload Image" name="submit">
		</form>
	</div>
</div>