<div class="footer">
	<ul id="footer_cols">
		<li>
			COLUMN 1
		</li>
		<li>
			COLUMN 2
		</li>
		<li>
			<div id="phone">
				<legend>Phone</legend>
				<ul>
					<li>01273 308268</li>
				</ul>
			</div>
			<div id="address">
				<legend>Address</legend>
				<ul>
					<li>37 Downs Valley Rd</li>
					<li>Brighton</li>
					<li>BN2 6RB</li>
				</ul>
			</div>
		</li>
		<li>
			<div id="availability">
				<legend>Availability</legend>
				<ul>
					<li>Monday: </li>
					<li>Tuesday: </li>
					<li>Wednesday:</li>
					<li>Thursday: </li>
					<li>Friday: </li>
					<li>Saturday: </li>
					<li>Sunday: </li>
				</ul>
			</div>
		</li>
	</ul>
</div>