<div class="about_us">
	<div id="brief">
		<h1>What?</h1>
		<p>We do a fair few things here at Scruffy Pigeon. As a new and very small, group we're attempting to stick our thumbs in as many pies as possible. As such, a lot of content on this site is just small projects and fun stuff we have worked on (this site being one of those!). For each project there'll be a new option on the site's navigation menu.</p>
	</div>

	<div id="bio">
		<h1>Who?</h1>
		<p>Currently, Scruffy Pigeon only consists of myself and my other half, with our inspiration coming from each other and our pet birds (2 doves and a cockatiel at the time of writing). Maybe we'll expand eventually, maybe we won't, WHO KNOWS?</p>
	</div>

	<div id="bio">
		<h1>Why?</h1>
		<p>Largely because I felt like it. I've been meaning to create a personal nexus of my projects and a homemade site seemed like an interesting solution. It'd make a handy portfolio as well as just a general business tool should I decide to try and make Scruffy Pigeon a legit thing in the future.</p>
	</div>
</div>
